---
- name: Install Clickhouse
  hosts: clickhouse
  become: true

  handlers:
    - name: Start clickhouse service
      become: true
      service:
        name: clickhouse-server
        state: restarted

    - name: Start vector service
      become: true
      service:
        name: vector
        state: restarted

  tasks:
    - name: Create directory for ssh-keys
      file: state=directory mode=0700 dest=/root/.ssh/
    - name: Adding rsa-key in /root/.ssh/authorized_keys
      copy: src=~/.ssh/id_rsa.pub dest=/root/.ssh/authorized_keys owner=root mode=0600
      ignore_errors: yes

    - block:
        - name: Get clickhouse distrib
          get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_all.deb"
            dest: "./{{ item }}_{{ clickhouse_version }}.deb"
            mode: '644'
          with_items: "{{ clickhouse_packages }}"
      rescue:
        - name: Get clickhouse distrib
          get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
            dest: "./clickhouse-common-static_{{ clickhouse_version }}.deb"
            mode: '644'
    - name: Install clickhouse
      become: true
      apt:
       deb: "{{ item }}"
       state: present
      with_items:
        - clickhouse-client_{{ clickhouse_version }}.deb
        - clickhouse-common-static_{{ clickhouse_version }}.deb
        - clickhouse-server_{{ clickhouse_version }}.deb
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

    - name: Get Vector distrib
      get_url:
        url: "https://packages.timber.io/vector/0.21.1/vector_0.21.1-1_amd64.deb"
        dest: "./vector_0.21.1-1.deb"
        mode: '644'
    - name: Install Vector
      become: true
      apt:
       deb: vector_0.21.1-1.deb
       state: present
    - name: Make dir
      file:
        path: /etc/vector
        state: directory
    - name: add conf
      template:
        src: ./templates/vector.yml.j2
        dest: /etc/vector/vector.toml
    - name: add service
      template:
        src: ./templates/vector.service.j2
        dest: /etc/systemd/system/vector.service
      notify: Start vector service
