{{- if .Values.version1.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappv1
  labels:
    app: my-app1
spec:
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      labels:
        app: my-app1
    spec:
      containers:
        - name: my-app1
          image: {{ .Values.version1.image }}
{{- end }}
