#cloud-config
package_update: true
package_upgrade: false
packages:
 - net-tools
runcmd:
 - echo "<html><body><h1>Welcome to the cat warehouse!</h1><p><a href='https://storage.yandexcloud.net/alyoshqas-bucket/cat.jpg'>Get a cat here (^..^)</a></p></body></html>" > /var/www/html/index.html
 - systemctl restart apache2 
