apiVersion: v1
kind: Service
metadata:
  name: my-app-nginx
  namespace: netology
spec:
  ports:
   - name: nginx
     port: 80
     protocol: TCP
     targetPort: 8080
  selector:
     app: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-multitool
  namespace: netology
spec:
  ports:
   - name: multitool
     port: 8180
     protocol: TCP
     targetPort: 8180
  selector:
     app: multitool
