---
- name: Install Clickhouse
  hosts: clickhouse
  vars_files:
    - [./group_vars/clickhouse.yml]
  become: true
  handlers:
    - name: Start clickhouse service
      become: true
      service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_all.deb"
            dest: "./{{ item }}_{{ clickhouse_version }}.deb"
            mode: '644'
          with_items: "{{ clickhouse_packages }}"
          tags:
          - clickhouse
      rescue:
        - name: Get clickhouse distrib
          get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
            dest: "./clickhouse-common-static_{{ clickhouse_version }}.deb"
            mode: '644'
          tags:
          - clickhouse
    - name: Install clickhouse from distrib
      become: true
      apt:
       deb: "{{ item }}"
       state: present
      with_items:
        - clickhouse-client_{{ clickhouse_version }}.deb
        - clickhouse-common-static_{{ clickhouse_version }}.deb
        - clickhouse-server_{{ clickhouse_version }}.deb
      notify: Start clickhouse service
      tags:
      - clickhouse
    - name: Create clickhouse config
      become: true
      template:
        src: clickhouse-server.yml.j2
        dest: /etc/clickhouse-server/config.xml
        mode: "0644"
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
      tags:
      - clickhouse

- name: Install Vector
  hosts: vector
  become: true
  handlers:
    - name: Start vector service
      become: true
      service:
        name: vector
        state: restarted
  tasks:
    - name: Get Vector distrib
      get_url:
        url: "https://packages.timber.io/vector/0.21.1/vector_0.21.1-1_amd64.deb"
        dest: "./vector_0.21.1-1.deb"
        mode: '644'
      tags:
      - vector
    - name: Install Vector from distrib
      become: true
      apt:
       deb: vector_0.21.1-1.deb
       state: present
      tags:
      - vector
    - name: Make directory
      file:
        path: /etc/vector
        state: directory
      tags:
      - vector
    - name: Add config
      template:
        src: vector.yml.j2
        dest: /etc/vector/vector.toml
        mode: "0644"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
      tags:
      - vector
    - name: Add service
      template:
        src: vector.service.j2
        dest: /etc/systemd/system/vector.service
        mode: 0644
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
      notify: Start vector service
      tags:
      - vector

- name: Install nginx on hosts lighthouse
  hosts: lighthouse
  vars_files:
    - [./group_vars/lighthouse.yml]
  handlers:
    - name: start-nginx
      become: true
      command: nginx
    - name: reload-nginx
      become: true
      command: nginx -s reload
  tasks:
    - name: Install nginx
      become: true
      apt:
        name: "{{ item }}"
        update_cache: yes
      loop:
        - nginx
        - curl
        - unzip
    - name: Create general config
      become: true
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify: reload-nginx

- name: Install Lighthouse
  hosts: lighthouse
  vars_files:
    - [./group_vars/lighthouse.yml]
  handlers:
    - name: reload-nginx
      become: true
      command: nginx -s reload
  pre_tasks:
    - name: Install git
      become: true
      apt:
        name: git
        state: present
  tasks:
    - name: download from git
      become: true
      git:
        repo: "{{ lighthouse_vcs }}"
        version: master
        dest: "{{ lighthouse_location_dir }}"
    - name:  Create  config
      become: true
      template:
        src: lighthouse.conf.j2
        dest: /etc/nginx/conf.d/default.conf
        mode: "0644"
      notify: reload-nginx
