---
- name: Install Clickhouse
  hosts: clickhouse
  vars_files:
    - [./group_vars/clickhouse.yml]
  become: true

  handlers:
    - name: Start clickhouse service
      become: true
      service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get clickhouse distrib
          get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/{{ item }}/{{ item }}_{{ clickhouse_version }}_all.deb"
            dest: "./{{ item }}_{{ clickhouse_version }}.deb"
            mode: '644'
          with_items: "{{ clickhouse_packages }}"
          tags:
          - clickhouse
      rescue:
        - name: Get clickhouse distrib
          get_url:
            url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse-common-static/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
            dest: "./clickhouse-common-static_{{ clickhouse_version }}.deb"
            mode: '644'
          tags:
          - clickhouse
    - name: Install clickhouse
      become: true
      apt:
       deb: "{{ item }}"
       state: present
      with_items:
        - clickhouse-client_{{ clickhouse_version }}.deb
        - clickhouse-common-static_{{ clickhouse_version }}.deb
        - clickhouse-server_{{ clickhouse_version }}.deb
      notify: Start clickhouse service
      tags:
      - clickhouse
    - name: Flush handlers
      meta: flush_handlers
      tags:
      - clickhouse
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
      tags:
      - clickhouse

- name: Install Vector
  hosts: vector
  become: true

  handlers:
    - name: Start vector service
      become: true
      service:
        name: vector
        state: restarted
  tasks:
    - name: Get Vector distrib
      get_url:
        url: "https://packages.timber.io/vector/0.21.1/vector_0.21.1-1_amd64.deb"
        dest: "./vector_0.21.1-1.deb"
        mode: '644'
      tags:
      - vector
    - name: Install Vector
      become: true
      apt:
       deb: vector_0.21.1-1.deb
       state: present
      tags:
      - vector
    - name: Make dir
      file:
        path: /etc/vector
        state: directory
      tags:
      - vector
    - name: add conf
      template:
        src: ./templates/vector.yml.j2
        dest: /etc/vector/vector.toml
      tags:
      - vector
    - name: add service
      template:
        src: ./templates/vector.service.j2
        dest: /etc/systemd/system/vector.service
      notify: Start vector service
      tags:
      - vector

- name: Install Lighthouse
  hosts: lighthouse
  vars_files:
    - [./group_vars/lighthouse.yml]
  become: true
  tasks:
