---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 192.168.56.11
      ansible_port: 22
      ansible_user: vagrant
      ansible_ssh_private_key_file: /home/sysadmin/Project/netology/resource/templates/08-ansible-02-playbook/playbook/.vagrant/machines/clickhouse-01/virtualbox/private_key



