apiVersion: v1
kind: Service
metadata:
  name: my-service-nodeport
  namespace: netology
spec:
  selector:
     app: my-app
  ports:
   - name: nginx
     port: 80
     nodePort: 30001
     protocol: TCP
   - name: multitool
     port: 8080
     nodePort: 30002
     protocol: TCP
  type: NodePort
