apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: netology
spec:
  selector:
     app: my-app
  ports:
   - name: nginx
     port: 9001
     protocol: TCP
     targetPort: 80
   - name: multitool
     port: 9002
     protocol: TCP
     targetPort: 8080
